version: '3.8'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
